language: node_js
node_js:
  - "6"
addons:
  ssh_known_hosts: troubadour.tk
before_install:
- openssl aes-256-cbc -K $encrypted_7fecd50c2af5_key -iv $encrypted_7fecd50c2af5_iv
  -in troubadour_key.enc -out troubadour_key -d
- bash scripts/install.sh
after_success:
- bash scripts/deploy.sh
