language: node_js
node_js:
  - "7"
addons:
  ssh_known_hosts: troubadour.tk
env:
  - CXX=g++-4.8
before_install:
- openssl aes-256-cbc -K $encrypted_7fecd50c2af5_key -iv $encrypted_7fecd50c2af5_iv
  -in troubadour_key.enc -out troubadour_key -d
- bash scripts/install.sh
before_script:
- npm run build
after_success:
- bash scripts/deploy.sh
